---
- hosts: syslog-ng-clients
  become: yes
  become_method: sudo

  vars:
   - docroot: /opt/deployment/nmon-logger

  tasks:

  - name: Create the system nmon account if required
    user: name=nmon comment="system account for nmon-logger" system=yes state=present

  - name: Create the /var/log/nmon-logger directory if required
    file: path=/var/log/nmon-logger owner=nmon state=directory mode=0755 recurse=no

  - name: Deploy nmon-logger binaries (/etc/nmon-logger)
    copy: src={{ docroot }}/nmon-logger-syslog-ng/etc/nmon-logger dest=/etc/
            owner=nmon group=nmon mode=0755

  - name: Deploy nmon-logger cron.d configuration
    copy: src={{ docroot }}/nmon-logger-syslog-ng/etc/cron.d/nmon-logger dest=/etc/cron.d/
            owner=nmon group=nmon mode=0644

  - name: Deploy nmon-logger logrotate.d configuration
    copy: src={{ docroot }}/nmon-logger-syslog-ng/etc/logrotate.d/nmon-logger dest=/etc/logrotate.d/
            owner=nmon group=nmon mode=0644

  - name: Deploy nmon-logger syslog-ng configuration
    copy: src={{ docroot }}/nmon-logger-syslog-ng/etc/syslog-ng/conf.d/nmon-logger.conf dest=/etc/syslog-ng/conf.d/
            owner=nmon group=nmon mode=0644
    notify:
        - restart syslog-ng

  handlers:

    - name: restart syslog-ng
      service: name=syslog-ng state=restarted
