---

- hosts: rsyslog-servers
  become: yes
  become_method: sudo

  vars:
   - docroot: /opt/deployment/nmon-logger
   - splunk_binpath: "{{ lookup('pipe', 'ls /opt/deployment/splunk_bin/splunkforwarder-*.tgz | head -1') }}"
   - splunk_installpath: /opt
   - splunk_appname: TA_syslog_nmon
   - splunk_indexer_adress: 192.168.33.1:9997
   - splunk_deploymentserver_adress: 192.168.33.1:8089
   - localzone: Europe/Paris

  tasks:

    #
    # For Ubuntu
    #

  - block:

    - name: Install rsyslog repo for Ubuntu

      # Add repo
      apt_repository: repo='ppa:adiscon/v8-stable' state=present
      when: ansible_distribution == 'Ubuntu'

    - name: Update cache for Ubuntu

      # Update apt cache
      apt: update_cache=yes

    - name: Update rsyslog for Ubuntu

      # Update package
      # Note: Using apt module does not seem to update rsyslog package, updating using command
      command: apt-get install -y rsyslog

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    #
    # For RHEL / Centos
    #

  - block:

    - name: Install rsyslog repo for RHEL/CentOS

      # Install repo file
      get_url: url=http://rpms.adiscon.com/v8-stable/rsyslog.repo dest=/etc/yum.repos.d/

    - name: Update rsyslog for RHEL/CentOS

      # Update package
      # Note: Using yum module does not seem to update rsyslog package, updating using command
      command: yum install -y rsyslog

    - name: Install minimal Perl environment
      yum: name=perl state=latest

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# Configure time zone
  - name: Set timezone variables
    copy: content='{{ localzone }}'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
    notify:
      - update timezone
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - block:

    # Create remote hosts directory for logging
    - name: Create the /var/log/remote-hosts directory (for Ubuntu/Debian with syslog owner)
      file: path=/var/log/remote-hosts owner=syslog group=syslog state=directory mode=0755 recurse=no

    # Create nmon performance directory for logging
    - name: Create the /var/log/nmon-performance directory (for Ubuntu/Debian with syslog owner)
      file: path=/var/log/nmon-performance owner=syslog group=syslog state=directory mode=0755 recurse=no

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - block:

    # Create remote hosts directory for logging
    - name: Create the /var/log/remote-hosts directory (for RHEL/CentOS with root owner)
      file: path=/var/log/remote-hosts owner=root group=root state=directory mode=0755 recurse=no

    # Create nmon performance directory for logging
    - name: Create the /var/log/nmon-performance directory (for RHEL/CentOS with root owner)
      file: path=/var/log/nmon-performance owner=root group=root state=directory mode=0755 recurse=no

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  # Set this host as a central syslog collector
  - name: Deploy rsyslog central configuration for global logging
    copy: src={{ docroot }}/vagrant-ansible-demo-rsyslog/99-central-server.conf dest=/etc/rsyslog.d/

  # Set this host as a central syslog collector
  - name: Deploy rsyslog central configuration for nmon performance
    copy: src={{ docroot }}/vagrant-ansible-demo-rsyslog/20-nmon-performance.conf dest=/etc/rsyslog.d/

  # Verify if Splunk Universal Forwarder is already installed
  - name: Check if Splunk Universal Forwarder path exists
    stat: path={{ splunk_installpath }}/splunkforwarder
    register: check_splunk_path

  # Copy and unarchive Splunk Universal Forwarder if not present
  - name: Copy and unarchive Splunk Universal Forwarder
    unarchive: src={{ splunk_binpath }} dest={{ splunk_installpath }}
    when: check_splunk_path.stat.exists == false

  # Start and accept licence
  - name: Start Splunk Universal Forwarder and accept licence
    command: "{{ splunk_installpath }}/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license"
    when: check_splunk_path.stat.exists == false

  # Enable boot-start
  - name: Enable boot start for Splunk Universal Forwarder
    command: "{{ splunk_installpath }}/splunkforwarder/bin/splunk enable boot-start"
    when: check_splunk_path.stat.exists == false

  # Configure Splunk forwarding
  - name: Configure Splunk forwarding
    command: "{{ splunk_installpath }}/splunkforwarder/bin/splunk add forward-server {{ splunk_indexer_adress }} -auth admin:changeme"
    ignore_errors: yes

  # Configure Splunk as a client of the deployment server
  - name: Configure Splunk as client of the deployment server
    command: "{{ splunk_installpath }}/splunkforwarder/bin/splunk set deploy-poll {{ splunk_deploymentserver_adress }} -auth admin:changeme"
    ignore_errors: yes

  # Verify if our custom app has been already created
  - name: Check if the custom app containing inputs.conf exists
    stat: path="/opt/splunkforwarder/etc/apps/{{ splunk_appname }}"
    register: check_splunk_app

  # Configure inputs.conf for nmon performance
  - name: Create custom app {{ splunk_appname }}
    file: path="{{ splunk_installpath }}/splunkforwarder/etc/apps/{{ splunk_appname }}/local" owner=root state=directory mode=0755

  - name: Configure custom app {{ splunk_appname }} inputs.conf
    copy: src={{ docroot }}/vagrant-ansible-demo-rsyslog/inputs.conf dest="{{ splunk_installpath }}/splunkforwarder/etc/apps/{{ splunk_appname }}/local/"
          owner=root
          group=root
          mode=0644
    when: check_splunk_app.stat.exists == false

  # Finally restart Splunk
  - name: Restart Splunk Universal Forwarder
    command: "{{ splunk_installpath }}/splunkforwarder/bin/splunk restart"

  # Last but not least, restart rsyslog (using module service causes some trouble, let's use simple command)
  - name: Restart rsyslog
    command: service rsyslog restart

  handlers:

    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

###############################################################

- hosts: rsyslog-clients
  become: yes
  become_method: sudo

  vars:
   - docroot: /opt/deployment/nmon-logger
   - localzone: Europe/Paris

  tasks:

    #
    # For Ubuntu
    #

  - block:

    - name: Install rsyslog repo for Ubuntu

      # Add repo
      apt_repository: repo='ppa:adiscon/v8-stable' state=present
      when: ansible_distribution == 'Ubuntu'

    - name: Update cache for Ubuntu

      # Update apt cache
      apt: update_cache=yes

    - name: Update rsyslog for Ubuntu

      # Update package
      # Note: Using apt module does not seem to update rsyslog package, updating using command
      command: apt-get install -y rsyslog

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    #
    # For RHEL / Centos
    #

  - block:

    - name: Install rsyslog repo for RHEL/CentOS

      # Install repo file
      get_url: url=http://rpms.adiscon.com/v8-stable/rsyslog.repo dest=/etc/yum.repos.d/

    - name: Update rsyslog for RHEL/CentOS

      # Update package
      # Note: Using yum module does not seem to update rsyslog package, updating using command
      command: yum install -y rsyslog

    - name: Install minimal Perl environment
      yum: name=perl state=latest

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# Configure time zone
  - name: Set timezone variables
    copy: content='{{ localzone }}'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
    notify:
      - update timezone

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  # Configure rsyslog on this host: Send data to rsyslog server, add rsyslog repo, update and upgrade rsyslog

  - name: Deploy rsyslog central configuration
    copy: src={{ docroot }}/vagrant-ansible-demo-rsyslog/01-central-client.conf dest=/etc/rsyslog.d/

  # NMON LOGGER installation

  - name: Create the system nmon account if required
    user: name=nmon comment="system account for nmon-logger" system=yes state=present

  - name: Create the /var/log/nmon-logger directory if required
    file: path=/var/log/nmon-logger owner=nmon state=directory mode=0755 recurse=no

  - name: Deploy nmon-logger binaries (/etc/nmon-logger)

  # Deploy /etc/nmon-logger by uncompressing the nmon-logger.tar.gz
    unarchive: src={{ docroot }}/nmon-logger-rsyslog/etc/nmon-logger.tar.gz dest=/etc/
                owner=nmon group=nmon mode=0755

  - name: Set owner and group owner for nmon-logger binaries (/etc/nmon-logger)
    file: path=/etc/nmon-logger owner="nmon" group="nmon" recurse="yes"

  - name: Deploy nmon-logger cron.d configuration
    copy: src={{ docroot }}/nmon-logger-rsyslog/etc/cron.d/nmon-logger dest=/etc/cron.d/
            owner=root group=root mode=0644

  - name: Deploy nmon-logger logrotate.d configuration
    copy: src={{ docroot }}/nmon-logger-rsyslog/etc/logrotate.d/nmon-logger dest=/etc/logrotate.d/
            owner=root group=root mode=0644

  - name: Deploy nmon-logger rsyslog.d configuration
    copy: src={{ docroot }}/nmon-logger-rsyslog/etc/rsyslog.d/20-nmon-logger.conf dest=/etc/rsyslog.d/
            owner=root group=root mode=0644

  # Last but not least, restart rsyslog (using module service causes some trouble, let's use simple command)
  - name: Restart rsyslog
    command: service rsyslog restart

  handlers:

    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
